name: CI/CD Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, redis, pdo_mysql

      - name: Install Lumen dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
        working-directory: backend/lumen-backend

      - name: Run Lumen tests
        run: php artisan test
        working-directory: backend/lumen-backend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Node dependencies
        run: npm install
        working-directory: backend/node-cache

      - name: Run Node tests
        run: npm test
        working-directory: backend/node-cache

      - name: Set up Frontend Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Frontend dependencies
        run: npm install
        working-directory: frontend/reactfrontend

      - name: Run Frontend tests
        run: npm test
        working-directory: frontend/reactfrontend
